version: "3"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: petalmd
      MYSQL_DATABASE: petalmd_db
      MYSQL_USER: petalmd_user
      MYSQL_PASSWORD: petalmd_pass
    ports:
          - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql                
    networks:
      - backend

  redis:
    image: redis:5.0.14 
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:7.3.0
    restart: always
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backend

  app:
    build: .
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - elasticsearch    
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/petalmd
    env_file:
      - .env      
    networks:
      - backend

volumes:
  redis:
  elasticsearch:
  mysql:

networks:
  backend:
    driver: "bridge"
